version: "3.8"

services:
  backend:
    container_name: sky-sight-backend
    build: ./backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    container_name: sky-sight-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  jupyter:
    container_name: sky-sight-jupyter
    hostname: jupyter
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./jupyter:/project
    working_dir: /project
    command: "bash run_jupyterlab.sh"

volumes:
  postgres_data:
