services:
  backend:
    container_name: sky-sight
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
