# Generated by Django 5.0.4 on 2024-04-24 00:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryForecast',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('pressao', models.FloatField()),
                ('velocidade_vento', models.FloatField()),
                ('rajada_vento', models.FloatField()),
                ('chuva', models.FloatField()),
            ],
        ),
    ]
