name: Deploy APS Sky Sight

on:
  push:
    branches:
      - main
    
jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate sha
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=${SHA}" >> $GITHUB_OUTPUT
    - name: Build docker image
      run: docker build -t rafaelmachadobr/sky-sight:${{ steps.generate_sha.outputs.sha }} -f backend/Dockerfile .

    - name: Log into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push rafaelmachadobr/sky-sight:${{ steps.generate_sha.outputs.sha }}
        docker tag rafaelmachadobr/sky-sight:${{ steps.generate_sha.outputs.sha }} rafaelmachadobr/sky-sight:latest
        docker push rafaelmachadobr/sky-sight:latest

  deploy:
    name: 'Deploy'
    needs: build-and-push
    runs-on: self-hosted

    steps:
        - name: Pull image from docker hub
          run: sudo docker pull rafaelmachadobr/sky-sight:latest

        - name: Remove docker container
          run: sudo docker rm -f sky-sight

        - name: Run docker container
          run: sudo docker run -d -p 8000:8000 \
            -e DEBUG="$DEBUG" \
            -e SECRET_KEY="$SECRET_KEY" \
            -e DJANGO_ALLOWED_HOSTS="$DJANGO_ALLOWED_HOSTS" \
            -e POSTGRES_ENGINE="$POSTGRES_ENGINE" \
            -e POSTGRES_DB="$POSTGRES_DB" \
            -e POSTGRES_USER="$POSTGRES_USER" \
            -e POSTGRES_PASSWORD="$POSTGRES_PASSWORD" \
            -e POSTGRES_HOST="$POSTGRES_HOST" \
            -e POSTGRES_PORT="$POSTGRES_PORT" \
            -e DATABASE="$DATABASE" \
            --name sky-sight rafaelmachadobr/sky-sight:latest
